
# Loads default set of integrations. Do not remove.
default_config:

# Loads my set of custom entities.
input_number: !include_dir_merge_named entities/input_number

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
