sensor:
  # === Outdoor Sensor ===
  - name: "Outdoor Temperature"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    value_template: >
      {% if value_json.ZbReceived.temp_outside.Temperature is defined %}
        {{ value_json.ZbReceived.temp_outside.Temperature }}
      {% else %}
        {{ states('sensor.outdoor_temperature') }}
      {% endif %}
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Outdoor Humidity"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    value_template: >
      {% if value_json.ZbReceived.temp_outside.Humidity is defined %}
        {{ value_json.ZbReceived.temp_outside.Humidity }}
      {% else %}
        {{ states('sensor.outdoor_humidity') }}
      {% endif %}
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Outside Temp LQI"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "LQI"
    value_template: >
      {% if value_json.ZbReceived.temp_outside.LinkQuality is defined %}
        {{ value_json.ZbReceived.temp_outside.LinkQuality }}
      {% else %}
        {{ states('sensor.outside_temp_lqi') }}
      {% endif %}
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Outside Temp Battery"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    value_template: >
      {% if value_json.ZbReceived.temp_outside.BatteryPercentage is defined %}
        {{ value_json.ZbReceived.temp_outside.BatteryPercentage }}
      {% else %}
        {{ states('sensor.outside_temp_battery') }}
      {% endif %}
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  # === Workshop Sensor ===
  - name: "Workshop Temperature"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    value_template: >
      {% if value_json.ZbReceived.temp_workshop.Temperature is defined %}
        {{ value_json.ZbReceived.temp_workshop.Temperature }}
      {% else %}
        {{ states('sensor.workshop_temperature') }}
      {% endif %}
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Workshop Humidity"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    value_template: >
      {% if value_json.ZbReceived.temp_workshop.Humidity is defined %}
        {{ value_json.ZbReceived.temp_workshop.Humidity }}
      {% else %}
        {{ states('sensor.workshop_humidity') }}
      {% endif %}
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Workshop Temp LQI"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "LQI"
    value_template: >
      {% if value_json.ZbReceived.temp_workshop.LinkQuality is defined %}
        {{ value_json.ZbReceived.temp_workshop.LinkQuality }}
      {% else %}
        {{ states('sensor.workshop_temp_lqi') }}
      {% endif %}
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Workshop Temp Battery"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    value_template: >
      {% if value_json.ZbReceived.temp_workshop.BatteryPercentage is defined %}
        {{ value_json.ZbReceived.temp_workshop.BatteryPercentage }}
      {% else %}
        {{ states('sensor.workshop_temp_battery') }}
      {% endif %}
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"