sensor:
  # === Outdoor Sensor ===
  - name: "Outdoor Temperature"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    value_template: "{{ value_json['ZbReceived']['0x5FCD'].Temperature }}"
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Outdoor Humidity"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    value_template: "{{ value_json['ZbReceived']['0x5FCD'].Humidity }}"
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Outside Temp Battery"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    value_template: "{{ value_json['ZbReceived']['0x5FCD'].BatteryPercentage }}"
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Outside Temp LQI"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "LQI"
    value_template: "{{ value_json['ZbReceived']['0x5FCD'].LinkQuality }}"
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  # === Workshop Sensor ===
  - name: "Workshop Temperature"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    value_template: "{{ value_json['ZbReceived']['0x5928'].Temperature }}"
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Workshop Humidity"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    value_template: "{{ value_json['ZbReceived']['0x5928'].Humidity }}"
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Workshop Temp Battery"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    value_template: "{{ value_json['ZbReceived']['0x5928'].BatteryPercentage }}"
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Workshop Temp LQI"
    state_topic: "tele/zbbridge/SENSOR"
    unit_of_measurement: "LQI"
    value_template: "{{ value_json['ZbReceived']['0x5928'].LinkQuality }}"
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"